### PR TITLE
Add latest env vars

### PR DESCRIPTION
**Pull request by CodeShakingSheep**
## Problem

Recently, 3 new env vars have been introduced which aren't reflected in this package's default env file. See https://github.com/invoiceninja/invoiceninja/blob/v5-stable/.env.example#L64

## Solution

Added env vars for Nordigen and Open Exchange to default env file

- NORDIGEN_SECRET_ID=
- NORDIGEN_SECRET_KEY=
- OPENEXCHANGE_APP_ID=

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by CodeShakingSheep** [comment]
!testme

**Comment by rndmh3ro** [comment]
Is there any benefit in settings these in the env-file but not making them configurable?

**Comment by CodeShakingSheep** [comment]
> Is there any benefit in settings these in the env-file but not making them configurable?

I agree with you that the goal would be to make them configurable in the future when this app has a config panel. For now, it's just to maintain a complete list of InvoiceNinja's env vars.

**Comment by rndmh3ro** [comment]
> For now, it's just to maintain a complete list of InvoiceNinja's env vars.

Well then you'd have to add some more variables.. :)

But either way since this doesn't really change anything, feel free to merge.

**Review by rndmh3ro — APPROVED** [review]

**Comment by CodeShakingSheep** [comment]
Ah ok, those were just the variables I noticed were missing. As I don't have write access to this repo directly, I cannot merge this PR. Could you either grant me write access or merge it yourself? Thanks.

**Pull request merged**
